### ISSUE TITLE
Generate unexpected notebook cell in Japanese Documentation

### ISSUE THREAD

**Issue by hurutoriya** [tensorflow/docs-l10n#134]
I found issues about after convert to docs that generated extra notebook cell.

- https://www.tensorflow.org/tutorials/keras/classification in Japanesse version

![image](https://user-images.githubusercontent.com/2786333/77142134-896c5780-6ac2-11ea-94f8-8e97e35c7521.png)

- Original: notebook 
- https://github.com/masa-ita/tf-docs/blob/b8cd622e042ce322345d5fa30858087ee1abcab1/site/ja/tutorials/keras/basic_classification.ipynb

**Comment by sfujiwara** [comment]
@lamberta The original notebook in docs-l10n repository does not include such an empty cell.
Is that a problem in Google's internal system building the documents from notebooks?

**Comment by lamberta** [comment]
Probably related to the `%tensorflow_version 2.x` that we need to include in Colab. See https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/keras/classification.ipynb
This block is stripped when imported into tensorflow.org.
But soon enough, Colab will default to TF 2 and we can remove these blocks throughout.

**Comment by MarkDaoust** [comment]
> But soon enough, Colab will default to TF 2 and we can remove these blocks throughout.

Done.
