### ISSUE TITLE
Some notebooks using: `tf-nightly-2.0-preview`

### ISSUE THREAD

**Issue by MarkDaoust** [tensorflow/docs-l10n#137]
This package does not exist anymore. Please upgrade all notebooks to use `%tensorflow_version 2x`.

https://github.com/tensorflow/docs-l10n/search?q=tf-nightly-2.0-preview&unscoped_q=tf-nightly-2.0-preview

**Comment by lamberta** [comment]
Broke this issue up on language to make it easier for reviewers:

* https://github.com/tensorflow/docs-l10n/issues/145
* https://github.com/tensorflow/docs-l10n/issues/146
* https://github.com/tensorflow/docs-l10n/issues/147
