### ISSUE TITLE
[ja] load_data/csv.ipynb using non-existant "Dataset.output_shapes".

### ISSUE THREAD

**Issue by MarkDaoust** [tensorflow/docs-l10n#138]
This tutorials is currently broken (also needs a `%tensorflow_version 2.x`):

https://github.com/tensorflow/docs-l10n/blob/master/site/ja/tutorials/load_data/csv.ipynb

**Comment by lamberta** [comment]
Please take a look REVIEWERS: @ohtaman @sfujiwara @masa-ita @AseiSugiyama @yukinagae @nuka137 @chie8842 @kiszk

You can try using the [nb_code_sync.py](https://github.com/tensorflow/docs/blob/master/tools/nb_code_sync.py) script to help keep notebooks up-to-date.

**Comment by AseiSugiyama** [comment]
I think this issue has been fixed by https://github.com/tensorflow/docs-l10n/pull/176 so we can close this issue safely.

@lamberta @MarkDaoust How do you think?

**Comment by lamberta** [comment]
Thanks, @AseiSugiyama !
