### ISSUE TITLE
[ja] Automatic proofreading on GitHub Actions

### ISSUE THREAD

**Issue by sfujiwara** [tensorflow/docs-l10n#144]
We, Japanese community members, are using a [proofreading tool](https://github.com/tfug/proofreading).

We want to apply the proofreading tool on CI and make Japanese contributors to pass it.
Thus, our questions are below:

**1. Could we create `docs-l10n/.github/workflows/ja.yml`?**

We want to define a GitHub Actions's workflow for Japanese documents proofreading.
The setting below will not affect non-japanese documents:

```yaml
on:
  push:
    paths:
      - 'site/ja/**'
```

**2. Could we use `docs-l10n/tools` directory to develop proofreading tool?**

I guess it's natural that the proofreading tool is in `docs-l10n/tools`.

If it's "no", however, we are planning to checkout [tfug/proofreading](https://github.com/tfug/proofreading) in GitHub Actions and apply it.
Actually, [current workflow](https://github.com/tensorflow/docs-l10n/blob/6cd120c79237361422f83df4f22c2f7760f5fa87/.github/workflows/ci.yaml) for tensorflow/docs-l10n checkout [tensorflow/docs](https://github.com/tensorflow/docs) repository and use `docs/tools/nbfmt.py`.

**Comment by lamberta** [comment]
Sounds good to me. But still figuring out adding `nbfmt.py` as CI using GitHub Actions. It seems there are a lot (security) restrictions if you want to automatically add commits on a pull requests. But if you just want to use it for pass/fail tests and surface that in the PR, that is more straightforward.

**Comment by sfujiwara** [comment]
Thanks.

> It seems there are a lot (security) restrictions if you want to automatically add commits on a pull requests

We are not planning to automatically add commits on CI. Just applying our proofreading tool for pass/fail tests. Translators should pass the test in their commits and PRs.

If it's okay, we are willing to make a PR to add `docs-l10n/.github/workflows/ja.yml`.

**Comment by lamberta** [comment]
Cool. Yeah, please submit a PR and we can go through it. I'm not familiar with all of your tooling, so will need you (or someone in the community) to maintain it. But sounds good to me 😀

**Comment by sfujiwara** [comment]
PR #185 is for this issue and it merged.
