### ISSUE TITLE
[ja] Remove references to tf-nightly-2.0-preview package

### ISSUE THREAD

**Issue by lamberta** [tensorflow/docs-l10n#145]
The `tf-nightly-2.0-preview` package does not exist anymore. Please upgrade all notebooks to use `%tensorflow_version 2.x` like:

```
try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass
```

Affects:

* [/site/ja/lite/convert/python_api.md](https://github.com/tensorflow/docs-l10n/blob/master/site/ja/lite/convert/python_api.md)
* [/site/ja/guide/function.ipynb](https://github.com/tensorflow/docs-l10n/blob/master/site/ja/guide/function.ipynb)
* [/site/ja/tutorials/load_data/csv.ipynb](https://github.com/tensorflow/docs-l10n/blob/master/site/ja/tutorials/load_data/csv.ipynb)

**Comment by lamberta** [comment]
REVIEWERS cc: @ohtaman @sfujiwara @masa-ita @AseiSugiyama @yukinagae @nuka137 @chie8842 @kiszk

**Comment by AseiSugiyama** [comment]
Thank you for your notification, we'll update & fix them.

**Comment by AseiSugiyama** [comment]
I think https://github.com/tensorflow/docs-l10n/pull/152 fixed this issue. However, We have to update these outdated documents.

- [/site/ja/lite/convert/python_api.md](https://github.com/tensorflow/docs-l10n/blob/master/site/ja/lite/convert/python_api.md)
- [ja/tutorials/load_data/csv.ipynb](https://github.com/tensorflow/docs-l10n/blob/master/site/ja/tutorials/load_data/csv.ipynb) (it's broken as mentioned  https://github.com/tensorflow/docs-l10n/issues/138)

I'm going to update them and make two PRs for each document.

**Comment by lamberta** [comment]
Thanks @AseiSugiyama for taking a look.

Now that Colab defaults to TF 2.2, we can remove the `%tensorflow_version 2.x` block from notebooks.

Mark just merged https://github.com/tensorflow/docs-l10n/pull/152 which should remove them, but we may need to keep an eye on any outstanding pull requests

**Comment by AseiSugiyama** [comment]
Right, I would like to contribute to the TF community to be an "eye" 👀 

By the way, I found it is hard to update translated documents to follow the original document since we lack the sync tool like `nb_code_sync.py` after separating docs repo and docs-l10n repo. Do you have any ideas about this?

**Comment by lamberta** [comment]
@AseiSugiyama Hello. `nb_code_sync.py` should still work, you can pass it the `--src` argument.
But, point taken, I'll look into streamlining that tool now that the repos are separate

**Comment by AseiSugiyama** [comment]
@lamberta How about the result of your taking a look? I think it is not obvious the way to maintain the `en` directory and other languages' directory that we can use `nb_code_sync.py` with git only because `docs` and `docs-l10n` are separated.

**Comment by lamberta** [comment]
Hi @AseiSugiyama , thanks for taking a look.
I made the command-line errors a little easier to read in https://github.com/tensorflow/docs-l10n/pull/175, but the script seems to work-as-intended:

```
# Install deps:
$ pip3 install --user absl-py

# Assume you've downloaded both tensorflow/docs and tensorflow/docs-l10n repos
$ cd docs-l10n

$ ./tools/nb_code_sync.py --src=../docs/site/en/guide/function.ipynb \
    ./site/ja/guide/function.ipynb

Error: Notebooks must have same amount of code cells to sync between.
Please manually compare the source and destination notebooks.
```

Unfortunately. these Japanese notebooks are quite out-of-date and missing a number of code cells that are in the en/ source-of-truth. This script assumes that the number of code cells matches between the two notebooks to properly sync.
Quickly looking at the [Japanese version](https://github.com/tensorflow/docs-l10n/blob/master/site/ja/guide/function.ipynb), I can see that it's missing the "Debugging" section in the [English version](https://github.com/tensorflow/docs/blob/master/site/en/guide/function.ipynb) (and maybe more).

For something like this, you'll have to manually look through and make sure it's structurally similar to the en/ version. `nb_code_sync.py` is really just meant to keep any code changes up-to-date and avoid too much drift.

**Comment by AseiSugiyama** [comment]
@lamberta Thank you for your kindly reporting! It sounds nice that we will be able to use the `nb_code_sync.py` after updating these three notebooks (maybe). I made a PR for csv.ipynb https://github.com/tensorflow/docs-l10n/pull/176 and try to update all these notebooks.

**Comment by AseiSugiyama** [comment]
I updated related documents by https://github.com/tensorflow/docs-l10n/pull/176 https://github.com/tensorflow/docs-l10n/pull/190 https://github.com/tensorflow/docs-l10n/pull/220 and they've been marged 🎉

I guess we can safely close this issue. Thank you for your work, @lamberta!

**Comment by lamberta** [comment]
Awesome. Thank you @AseiSugiyama this is great
