### ISSUE TITLE
[ko] Remove references to tf-nightly-2.0-preview package

### ISSUE THREAD

**Issue by lamberta** [tensorflow/docs-l10n#147]
The `tf-nightly-2.0-preview` package does not exist anymore. Please upgrade all notebooks to use `%tensorflow_version 2.x` like:

```
try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass
```

Affects:

* [/site/ko/tutorials/keras/text_classification.ipynb](https://github.com/tensorflow/docs-l10n/blob/master/site/ko/tutorials/keras/text_classification.ipynb)
* [/site/ko/tutorials/keras/overfit_and_underfit.ipynb](https://github.com/tensorflow/docs-l10n/blob/master/site/ko/tutorials/keras/overfit_and_underfit.ipynb)
* [/site/ko/tutorials/structured_data/feature_columns.ipynb](https://github.com/tensorflow/docs-l10n/blob/master/site/ko/tutorials/structured_data/feature_columns.ipynb)

**Comment by lamberta** [comment]
REVIEWERS cc: @rickiepark @cre8tor @choiuijin1125 @JKIsaacLee @NoelBird @wckim @eat-toast @jaketae

**Comment by jaketae** [comment]
I’ll work on the fix today and open a PR!

**Comment by rickiepark** [comment]
Thanks @jaketae :)
