### ISSUE TITLE
[ko] Notebooks out of sync

### ISSUE THREAD

**Issue by yashk2810** [tensorflow/docs-l10n#184]
Hello,

Please sync the ko notebooks to the source of truth notebooks using the nb_code_sync tool here( https://github.com/tensorflow/docs-l10n/blob/master/tools/nb_code_sync.py).

Currently, many of them are failing.

**Comment by lamberta** [comment]
Adding [REVIEWERS](https://github.com/tensorflow/docs-l10n/blob/master/site/ko/REVIEWERS): @rickiepark @cre8tor @choiuijin1125 @JKIsaacLee @NoelBird @wckim @eat-toast @jaketae 
Please take a look.

@yashk2810 I think the community could benefit from more explicit guidance. Which notebooks? And do you know why? It seems odd a bunch started failing since their haven't been any new merges this week.

**Comment by yashk2810** [comment]
The builds have been failing for a long time. I am increasing the timeout for those, but for example `style_transfer` still has mentions of tensorflow.contrib.

```
ModuleNotFoundError: No module named 'tensorflow.contrib'
ModuleNotFoundError: No module named 'tensorflow.contrib'

+ delete_or_move site/ko/tutorials/generative/style_transfer.ipynb
```

I can get you the list of notebooks that fail, but it would still be nice to sync atleast all the guides and tutorials directory since some of the code has been updated there.

A notebook working is not indicative of the latest code being in them. It can continue to work due to TF's backward compatibility guarantees.

**Comment by jaketae** [comment]
I will take a look at `style_transfer.ipynb` and file a PR today. @yashk2810 @lamberta Sorry if this is a basic question, but is there a systematized way of making sure that our code base is in sync? Reviewers can take a look once in a while, but I feel like doing so manually is ineffective and creates room for error.

**Comment by yashk2810** [comment]
Yup, you can use the nb_code_sync tool.
https://github.com/tensorflow/docs-l10n/blob/master/tools/nb_code_sync.py

**Comment by lamberta** [comment]
Hi @jaketae 

> is there a systematized way of making sure that our code base is in sync

Nothing automated across the entire code base. We get notifications when a notebook breaks but, as @yashk2810 mentioned, it may still contain out-of-date code that happens to work.

[nb_code_sync.py](https://github.com/tensorflow/docs-l10n/blob/master/tools/nb_code_sync.py) is useful for detecting when *code cells* are out of sync with the `en/` source. It's far from perfect, but has been used successfully by the community ([example](https://github.com/tensorflow/docs-l10n/pull/117)):

```
# Install deps:
$ pip3 install -U absl-py

$ ./tools/nb_code_sync.py --src=../docs/site/en/notebook.ipynb \
    ./site/<lang>/notebook.ipynb
```

(Check the help text at the top of the file for git usage to save translated comments, etc.)

**Comment by jaketae** [comment]
Thank you very much for the pointers! [nb_code_sync.py](https://github.com/tensorflow/docs-l10n/blob/master/tools/nb_code_sync.py) seems like a great handle little tool to better maintain the notebooks we have at the moment. I'll definitely take a look and try using it myself.

**Comment by yashk2810** [comment]
These are the notebooks that failed:

site/ko/tutorials/images/segmentation.ipynb
site/ko/tutorials/generative/style_transfer.ipynb
site/ko/tutorials/distribute/save_and_load.ipynb
site/ko/tutorials/distribute/multi_worker_with_keras.ipynb
site/ko/tutorials/keras/save_and_load.ipynb
site/ko/swift/python_interoperability.ipynb
site/ko/guide/random_numbers.ipynb

**Comment by yashk2810** [comment]
For the swift notebook, please save the outputs in it.

**Comment by jaketae** [comment]
@lamberta @yashk2810 Apologies for the delay, I got carried away by other things yesterday. I just ran the command

```
python ./tools/nb_code_sync.py site/ko/tutorials/generative/style_transfer.ipynb --site_root ../docs/site/en --src ../docs/site/en/tutorials/generative/style_transfer.ipynb
```

but was returned with this error:

```
Error: Notebooks must have same amount of code cells to sync between.
Please manually compare the source and destination notebooks.
```

So it seems like the way to go about this would be to manually go back and forth to check if the notebooks are in sync. I can definitely do that, but before I begin engaging in menial work, I was wondering if there are any other options at my disposal. 

Thank you again for the help!

**Comment by jaketae** [comment]
> For the swift notebook, please save the outputs in it.

@rickiepark I'm not well-acquainted with how Swift notebooks are maintained. Should this be added as an instruction on README for community translators?

**Comment by rickiepark** [comment]
Hi @jaketae 
Yes, there is a note in README: "S4TF 노트북은 꼭 출력 결과가 포함되어야 합니다" :)
Please check https://github.com/tensorflow/docs-l10n/tree/master/site/ko

**Comment by jaketae** [comment]
@rickiepark Oops, my bad. I should have checked before I tagged you. My apologies, and thank you for the confirmation!

**Comment by lamberta** [comment]
Hi @jaketae 
Yes, unfortunately the nb_code_sync tool assumes the same amount of code cells in both source and translation notebook. If they don't match, that probably indicates the translation is quite out of date.
I'll think about better ways to automate this. I could make sure cell metadata is the same across both notebooks, but we haven't enforced that.

**Comment by rickiepark** [comment]
For this issue, I send PRs #9, #197, #198, 

Hi @jaketae, there are your commits in my PRs #197, #198
So these PRs may need your comment(@googlebot I consent.)

Thanks

**Comment by jaketae** [comment]
@rickiepark Just did, and I think all checks have passed. Thank you for letting me know! I'll also take a look at the PRs and review them if I can.

**Comment by yashk2810** [comment]
These notebooks are failing:

https://github.com/tensorflow/docs-l10n/blob/master/site/ko/tutorials/distribute/multi_worker_with_keras.ipynb
https://github.com/tensorflow/docs-l10n/blob/master/site/ko/tutorials/keras/text_classification_with_hub.ipynb
https://github.com/tensorflow/docs-l10n/blob/master/site/ko/tutorials/keras/save_and_load.ipynb
https://github.com/tensorflow/docs-l10n/blob/master/site/ko/tutorials/images/segmentation.ipynb
https://github.com/tensorflow/docs-l10n/blob/master/site/ko/swift/python_interoperability.ipynb
https://github.com/tensorflow/docs-l10n/blob/master/site/ko/guide/function.ipynb
https://github.com/tensorflow/docs-l10n/blob/master/site/ko/guide/migrate.ipynb

Please sync the code up with `en/`. The text update can be done in a separate PR so that the notebooks will start passing.

**Comment by rickiepark** [comment]
Hi @yashk2810 , Thanks for letting me know that. :)

multi_worker_with_keras, save_and_load, python_interoperability is pending at #198 , but I check again if there are recent changes.
And I also try to fix others ASAP! :)
