### ISSUE TITLE
How to translate the content under tensorflow.org/resources/learn-ml?

### ISSUE THREAD

**Issue by mohamed-ali** [tensorflow/docs-l10n#224]
Some resources under tensorflow.org/resources/learn-ml like this one https://developers.google.com/machine-learning/crash-course are useful and are already translated to multiple languages, therefore, I want to translate them into Arabic. However, their source code isn't in this repository and I couldn't find it in other repositories. 

So, could explain the procedure to translate them? 

Thanks.

**Comment by mohamed-ali** [comment]
@lamberta  Could you help regarding this enquiry? Thanks.

**Comment by lamberta** [comment]
Sorry for the delay, @mohamed-ali 

The [ML Crash Course](https://developers.google.com/machine-learning/crash-course) is not part of tensorflow.org so out-of-scope for this project.

The community translations here in the docs-l10n repo are restricted to technical content (guides and tutorials). Landing pages, such as the [resources/learn-ml](https://www.tensorflow.org/resources/learn-ml) are translated using a different process (with different prioritization), so also out-of-scope for this project. Thanks
