### ISSUE TITLE
Tensorflowのチュートリアル「Overfit and underfit」の不備

### ISSUE THREAD

**Issue by jsato0807** [tensorflow/docs-l10n#228]
「初心者のためのTensorFlow 2.0 入門」のチュートリアルにある「overfit and underfit」で日本語版では、Google Colabで実行するとメモリ不足でクラッシュする。

**Comment by AseiSugiyama** [comment]
Hi, @jsato0807 thank you for your reporting! Let me take a look.

**Comment by AseiSugiyama** [comment]
I succeed to reproduce your reporting issue. We can reproduce it from https://www.tensorflow.org/tutorials/keras/overfit_and_underfit?hl=ja

I guess we can fix this issue by updating it, however, I found another issue on the original English notebook. To keep the English notebook as the single source of the truth, I will try to fix this issue by following steps:

1. Fix the original English notebook.
2. Update [overfit and underfit](https://www.tensorflow.org/tutorials/keras/overfit_and_underfit?hl=ja) notebook.

Again, thank you for your reporting!

**Comment by AseiSugiyama** [comment]
念のため日本語でも書いておきます。

手元で再現できました。最新版の英語の notebook に追従することで解決できそうですが、英語の notebook にも課題が発見されたという状況です。ドキュメントについては英語版を正とするポリシーなので、次の順で対応する予定です。

1. 英語版の課題の解決
2. 日本語版のアップデート

なので、少し時間かかってしまいますが、お待ちいただけるとありがたいです。

**Comment by AseiSugiyama** [comment]
I created the PR for step 1. https://github.com/tensorflow/docs/pull/1580

**Comment by jsato0807** [comment]
わかりました。ありがとうございます。

**Comment by lamberta** [comment]
https://github.com/tensorflow/docs/pull/1580 was merged so I'm going to close this issue.
Feel free to reopen if there's more to be done. Thanks!
