### ISSUE TITLE
bn - Add support for Bengali Language

### ISSUE THREAD

**Issue by tazihad** [tensorflow/docs-l10n#239]
Requesting a new feature. Bengali language translation.
I am willing to contribute.

**Comment by lamberta** [comment]
Hi @tazihad  , Sorry for the delay.
Unfortunately, each language (community-driven or officially supported) adds additional maintenance costs so we're prioritizing new languages based on a combination of site metrics and community support. No plans to add Bengali translations but will keep an eye on site. Thanks
