### ISSUE TITLE
Tensorflowの「overfit and underfit」の不備

### ISSUE THREAD

**Issue by jsato0807** [tensorflow/docs-l10n#245]
%tensorboard --logdir {logdir}/sizes　を実行すると　UsageError: Line magic function `%tensorboard` not found.　となる。

**Comment by AseiSugiyama** [comment]
Hi, this is the same issue described in https://github.com/tensorflow/docs/pull/1580 I believe this issue will be fixed by merging the PR.

**Comment by jsato0807** [comment]
thank you for teaching me about it.

**Comment by lamberta** [comment]
https://github.com/tensorflow/docs/pull/1580 is merged. Thank you
