### ISSUE TITLE
Little bug? 

### ISSUE THREAD

**Issue by deflorator1980** [tensorflow/docs-l10n#260]
I think it's a bug
![image](https://user-images.githubusercontent.com/7847271/84676251-f498bf00-af35-11ea-8bd4-845697e447e0.png)

**Comment by kruzes1** [comment]
I want to debug it... please assign me this role. I am starting my journey in opensource world. give me an opportunity to work on it.

**Comment by lamberta** [comment]
Not sure, but I believe you're looking at this notebook: https://github.com/tensorflow/docs/blob/master/site/en/r1/tutorials/load_data/images.ipynb

It looks fixed so closing this issue. But, FYI, the TF 1.x notebooks have been archived and are no longer maintained. Thanks
