### ISSUE TITLE
Portuguese version

### ISSUE THREAD

**Issue by lmagoncalo** [tensorflow/docs-l10n#72]
Is it possible to correct some Portuguese notebooks, as they have some typos? I'm a Portuguese native speaker.

**Comment by lamberta** [comment]
Yes, these are community-provided translations—please join as a contributor or a reviewer and send a pull request.

More info available here: https://www.tensorflow.org/community/contribute/docs#community_translations
and in README docs in this repo: https://github.com/tensorflow/docs-l10n/tree/master/site

If you add your github username to the REVIEWERS file: https://github.com/tensorflow/docs-l10n/blob/master/site/pt/REVIEWERS
you'll get notified on new pull requests for Portuguese. Thanks!
